In [1]:
conda install numpy

Channels:
 - defaults
Platform: osx-arm64
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    archspec-0.2.3             |     pyhd3eb1b0_0          47 KB
    ca-certificates-2024.9.24  |       hca03da5_0         131 KB
    certifi-2024.8.30          |  py311hca03da5_0         165 KB
    conda-24.9.2               |  py311hca03da5_0         1.2 MB
    frozendict-2.4.2           |  py311hca03da5_0          38 KB
    openssl-3.0.15             |       h80987f9_0         4.3 MB
    ------------------------------------------------------------
                                           Total:         5.9 MB

The following NEW packages will be INSTALLED:

  frozendict         pkgs/main/osx-arm64::frozendict-2.4.2-py311hca03da5_0 

The following packages will be UPDATED:

  

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]

In [4]:
#numpy arrays

In [5]:
 np.array(my_list) #listeyi array liste dönüştürür

array([1, 2, 3, 4, 5])

In [6]:
array_list = np.array(my_list)

In [7]:
type(array_list)

numpy.ndarray

In [8]:
array_list[1] #index mantığıyla çalışıyor

2

In [10]:
array_list[4] = 6

In [11]:
print(array_list)

[1 2 3 4 6]


In [15]:
array_list.max() #max değeri gösterir

6

In [16]:
array_list.min() #min değeri gösterir

1

In [17]:
array_list.mean() #ortalama değeri gösterir

3.2

In [1]:
matrix_list = [(1,1,1),(1,0,1),(1,0,0),(0,0,1)] 

In [3]:
import numpy as np 

In [6]:
np_matrix_list = np.array(matrix_list)

In [8]:
type(np_matrix_list)

numpy.ndarray

In [12]:
np_matrix_list[0][0:] #index mantığıyla çalışır

array([1, 1, 1])

In [13]:
np_matrix_list.shape #ölçülerini gösterir(satır-sütun bazında)

(4, 3)

In [14]:
#arrange
#nump kütüphanesinin ferdi
#arrange ile range farkı çıktı türüdür arrange dönenleri liste olarak tutar

#np.arange(start, stop, step)

In [15]:
range(0,10) 

range(0, 10)

In [16]:
type(range(0,10))

range

In [17]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
#aynı şeyi np kütüphanesi tanımlıyken daha kapsamlı yazdırabiliriz
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
type(np.arange(0,10))

numpy.ndarray

In [22]:
np.arange(0,50,5) #0dan başla 49a kadar 5er 5er 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
print(np.zeros(5)) #0dan 5 tane yazırmak için
print(np.ones(5)) # 1den 5 tane yazdırmak için

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [27]:
type(np.zeros)

builtin_function_or_method

In [31]:
#2li matrix şeklinde de kullanabiliriz
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [44]:
np.zeros((1,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [1]:
import numpy as np 

In [2]:
#linspace belirli başlangıç bitiş arasında eşit aralıklı sayılar üretmeye yarar
#np.arange farkı adım değerini değil oluşturulacak eleman saysısını belritir

#np.linspace(start, stop, num)
#num: dizide kaç eleman olacağını belirtir


np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
np.linspace(1, 4, 5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [18]:
#random rastgele sayı ve dizi üretir.
np.random.rand(4,2) #4x2 boyutunda rastgele sayılardan oluşan matris 
#0-1 arasında eşit dağılım rastgele üretir

array([[0.37388921, 0.41434136],
       [0.26937761, 0.51861752],
       [0.77814118, 0.72652411],
       [0.76163347, 0.60909818]])

In [19]:
np.random.randn(3) #5 elemanlı normal dağılım
#ort 0, stan.sapma 1 rastgeel sayılar 

array([-1.00645459,  0.13861849,  0.5156328 ])

In [22]:
np.random.randint(2,5,size=3) #2-5 arasında 3 rastgele sayı
#belirli aralıkta tam sayı üretir

array([3, 2, 4])

In [23]:
np.random.choice([1,2,3,4,5], size=2) #başta tanımlanan diziden rastgele 2 değer seçer
#veri setinden rastgele seçimler yaptırır

array([4, 2])

In [25]:
#np.array() = arr diye tanımlanır adetten gibi bir şey

numpy arrays methods

In [26]:
np_list = np.arange(1,20)

In [28]:
np_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [29]:
np_list[5] #index mantığı var,

6

In [31]:
np_list[2:8] #2. elemendan 8.elemana getir

array([3, 4, 5, 6, 7, 8])

In [1]:
import numpy as np

In [2]:
np_list1 = np.arange(1,15)

In [5]:
np_list1[2:6] = -8 #belirli aralığı dönüştürür

In [6]:
np_list1

array([ 1,  2, -8, -8, -8, -8,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
#np listlerinde olmaması ama bilinmesi gereken özellik
np_list2 = np_list1[8:13]

In [12]:
np_list2

array([ 9, 10, 11, 12, 13])

In [13]:
np_list2[:] = 0

In [14]:
np_list2

array([0, 0, 0, 0, 0])

In [15]:
#bunun değişmemiş olması gerekirdi
np_list1

array([ 1,  2, -8, -8, -8, -8,  7,  8,  0,  0,  0,  0,  0, 14])

In [16]:
np_list1 > 3

array([False, False, False, False, False, False,  True,  True, False,
       False, False, False, False,  True])

In [17]:
 np_list3 = np_list1 > 3

In [18]:
np_list3

array([False, False, False, False, False, False,  True,  True, False,
       False, False, False, False,  True])

In [19]:
np_list1[np_list3]

array([ 7,  8, 14])

In [2]:
import numpy as np

In [3]:
np_list = np.arange(0,21)

In [5]:
np_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
np_list + np_list #np list mantığında listeleri toplaya bilirsin

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [9]:
np_list * np_list #çarpabilirsin

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [10]:
np_list / np_list #ama 0dan ötürü bölemezsin

/var/folders/2z/4s7ww8052797tq_0204m3t2r0000gn/T/ipykernel_3009/395153612.py:1: RuntimeWarning: invalid value encountered in divide
  np_list / np_list #ama 0dan ötürü bölemezsin


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])